services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    init: true
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
    # env_file: ./.env  # Uncomment if .env file exists
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db_data: